// Pares [español, inglés] ya traducidos a mano, extraídos del antiguo src/i18n.ts.
// Se usan para precargar traducciones_cache al arrancar el servidor, así los textos
// de navegación/paneles más comunes tienen traducción instantánea sin gastar la cuota
// de DeepL ni esperar la llamada — todo lo demás se traduce bajo demanda y se cachea igual.
module.exports = [
    ["Inicio","Home"],
    ["Mapa de zonas","Zone Map"],
    ["Sensores IoT","IoT Sensors"],
    ["Sobre nosotros","About Us"],
    ["Reportes","Reports"],
    ["Alertas","Alerts"],
    ["Configuración","Settings"],
    ["Usuarios","Users"],
    ["Principal","Main"],
    ["Ciudadano","Citizen"],
    ["Administración","Administration"],
    ["Bienvenido a AquaFlow SV","Welcome to AquaFlow SV"],
    ["Resumen general del sistema","System overview & real-time telemetry"],
    ["Mapa de Zonas","Zone Map"],
    ["Gran San Salvador","Greater San Salvador area"],
    ["Dispositivos de medición en tiempo real","Real-time measurement devices"],
    ["Sobre Nosotros","About Us"],
    ["Conoce nuestra historia, misión y equipo","Our story, mission & team"],
    ["Gestión de Usuarios","User Management"],
    ["Control de acceso y administración de roles","Access control & role administration"],
    ["Reportes Ciudadanos","Citizen Reports"],
    ["Gestión de incidencias y comentarios","Incident tracking & comments"],
    ["Alertas del Sistema","System Alerts"],
    ["Notificaciones críticas e incidencias activas","Critical notifications & active issues"],
    ["Preferencias del sistema y umbrales","System preferences & thresholds"],
    ["Monitoreo Hídrico IoT","Water Monitoring IoT"],
    ["Gran San Salvador · El Salvador","Greater San Salvador · El Salvador"],
    ["Sistema de Monitoreo Hídrico","Water Monitoring System"],
    ["Datos en vivo","Live Data"],
    ["Zonas Monitoreadas","Monitored Zones"],
    ["operativas","operational"],
    ["Sensores Activos","Active Sensors"],
    ["1 piloto USB en vivo","1 live USB pilot"],
    ["pendientes","pending"],
    ["Alertas Activas","Active Alerts"],
    ["Presión crítica o avisos","Critical pressure or notices"],
    ["Tendencia de Presión","Pressure Trend"],
    ["Últimas 6 horas · PSI por zona real","Last 6 hours · PSI per real zone"],
    ["Estado Actual","Current Status"],
    ["Presión por zona","Pressure per zone"],
    ["Ver mapa →","View map →"],
    ["Operativas","Operational"],
    ["En Alerta / Críticas","Alert / Critical"],
    ["Caudal Actual","Current Flow Rate"],
    ["Flujo por zona · L/min","Flow per zone · L/min"],
    ["Resumen Operativo Real","Real Operational Summary"],
    ["Todas las zonas monitoreadas","All monitored zones"],
    ["Zona","Zone"],
    ["Presión","Pressure"],
    ["Flujo","Flow Rate"],
    ["Estado","Status"],
    ["Gran San Salvador","Greater San Salvador"],
    ["Ubicación y estado en tiempo real de todas las zonas de monitoreo","Real-time location and status of all monitoring zones"],
    ["Ver Sensores IoT","View IoT Sensors"],
    ["Total zonas","Total Zones"],
    ["Monitoreadas","Monitored"],
    ["Óptimo / Estable","Optimal / Stable"],
    ["Con incidencia","With Issues"],
    ["Alerta / Crítico","Alert / Critical"],
    ["Mapa Interactivo — San Salvador","Interactive Map — San Salvador"],
    ["Haz clic en los marcadores para ver detalles de cada zona","Click on markers to view details for each zone"],
    ["Mostrar todas","Show all"],
    ["Detalles de Ubicaciones Reales","Real Location Details"],
    ["Coordenadas exactas y lecturas dinámicas por zona","Exact coordinates and dynamic zone metrics"],
    ["Coordenadas","Coordinates"],
    ["Leyenda de estados","Status Legend"],
    ["Dispositivos IoT","IoT Devices"],
    ["Sensores de Medición","Measurement Sensors"],
    ["Monitoreo en tiempo real de la red de sensores","Real-time monitoring of the sensor network"],
    ["Dispositivo real","Real device"],
    ["Sensor de Flujo (Arduino piloto)","Flow Sensor (Pilot Arduino)"],
    ["Conectado por USB · Puerto serie activo","Connected via USB · Serial port active"],
    ["En vivo","Live"],
    ["Desconectado","Disconnected"],
    ["Flujo","Flow"],
    ["Sin datos recientes del dispositivo","No recent data from device"],
    ["Red simulada (datos de ejemplo)","Simulated Network (Sample Data)"],
    ["Activos","Active"],
    ["Transmitiendo datos","Transmitting data"],
    ["Inactivos","Inactive"],
    ["Requieren atención","Need attention"],
    ["Total en Red","Total Network"],
    ["Todos","All"],
    ["Batería","Battery"],
    ["No hay sensores con este filtro.","No sensors found with this filter."],
    ["Transformando el monitoreo hídrico en El Salvador","Transforming water monitoring in El Salvador"],
    ["AquaFlow SV es una plataforma tecnológica concebida para brindar supervisión en tiempo real, alertas preventivas y control inteligente del suministro de agua potable en los municipios del Gran San Salvador.","AquaFlow SV is a technology platform designed to provide real-time supervision, preventive alerts, and intelligent control of drinking water supply in Greater San Salvador."],
    ["Isotipo Oficial 2026","Official Isotype 2026"],
    ["Nuestra Misión","Our Mission"],
    ["Proveer una plataforma integral de monitoreo hídrico que combine dispositivos IoT, mapas interactivos de geolocalización e inteligencia artificial para detectar desabastecimientos, fluctuaciones de presión y fugas, garantizando un servicio más transparente y eficiente para la comunidad salvadoreña.","Provide a comprehensive water monitoring platform combining IoT devices, interactive map geolocation, and artificial intelligence to detect outages, pressure fluctuations, and leaks."],
    ["Nuestra Visión","Our Vision"],
    ["Ser la solución de telemetría e infraestructura digital referente en El Salvador, empoderando a instituciones, técnicos y ciudadanos con información precisa para la toma de decisiones sostenibles en el cuidado y gestión del agua potable.","Be the leading telemetry and digital infrastructure solution in El Salvador, empowering institutions, technicians, and citizens with accurate information for sustainable water management."],
    ["Innovación Tecnológica","Technological Innovation"],
    ["Pilares Clave de AquaFlow SV","Key Pillars of AquaFlow SV"],
    ["Cobertura Actual en el Gran San Salvador","Current Coverage in Greater San Salvador"],
    ["Zonas monitoreadas activamente por la red de sensores","Zones actively monitored by the sensor network"],
    ["Talento y Compromiso","Talent & Commitment"],
    ["Equipo de Desarrollo","Development Team"],
    ["Estudiantes detrás de la creación de AquaFlow SV","Students behind the creation of AquaFlow SV"],
    ["Registro y seguimiento de incidencias de agua potable","Tracking and management of drinking water incidents"],
    ["Crear Reporte","Create Report"],
    ["Total Reportes","Total Reports"],
    ["Pendientes","Pending"],
    ["Resueltos","Resolved"],
    ["Nuevo Reporte de Incidencia","New Incident Report"],
    ["Usuario / Nombre","User / Name"],
    ["Zona / Sector","Zone / Sector"],
    ["Tipo de Incidencia","Incident Type"],
    ["Comentario / Descripción del problema","Comment / Description of issue"],
    ["Enviar Reporte","Submit Report"],
    ["Notificaciones críticas e incidencias activas en la red","Critical notifications and active network issues"],
    ["Presión Crítica","Critical Pressure"],
    ["Resolver Alerta","Resolve Alert"],
    ["Marcar como leída","Mark as read"],
    ["Configuración del Sistema","System Settings"],
    ["Personaliza las preferencias y umbrales de AquaFlow SV","Customize system preferences and AquaFlow SV thresholds"],
    ["Tema del sistema","System Theme"],
    ["Notificaciones","Notifications"],
    ["Control de acceso y administración de roles","Access control and role administration"],
    ["Usuario","User"],
    ["Correo Electrónico","Email Address"],
    ["Rol","Role"],
    ["Estado de Verificación","Verification Status"],
    ["Acciones","Actions"],
    ["Iniciar sesión","Log in"],
    ["Cerrar sesión","Log out"],
    ["Guardar cambios","Save changes"],
    ["Cancelar","Cancel"],
    ["Confirmar","Confirm"],
    ["Eliminar","Delete"],
    ["Editar","Edit"],
    ["Cargando...","Loading..."],
    ["Verificado","Verified"],
    ["Pendiente","Pending"],
    ["Administrador","Administrator"],
    ["Técnico","Technician"]
];
