; PlatformIO — AquaFlow SV (nodo de telemetría)
; Placa: Arduino Mega 2560

[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino

; Velocidad del Monitor Serie (coincide con Serial.begin en el código)
monitor_speed = 9600

; Librerías necesarias (PlatformIO las descarga solo al compilar)
lib_deps =
    marcoschwartz/LiquidCrystal_I2C@^1.1.4

; Si el puerto no se detecta solo, descomenta y ajusta (ej. COM4):
; upload_port = COM4
; monitor_port = COM4
